### ISSUE TITLE
Wrong file content/ex5/ex5.ipynb

### ISSUE THREAD

**Issue by quantumAnsatz** [qiskit-community/ibm-quantum-challenge-2021#123]
In the file qiskit-community/bm-quantum-challenge-2021/content/ex5/ex5.ipynb the Jupyter Notebook includes a solution of problem 5 and not an empty problem. It should include an unsolved version as the rest of solutions are in /solutions by authors/ .

**Comment by HuangJunye** [comment]
Thanks for reporting this issue. This should be fixed now.
